name: Tag major version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: 'v1.0.0'
      prefix:
        required: false
        type: string
        default: 'v'

jobs: 
  tag-version:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - name: Create Tag
      uses: actions/github-script@v7
      with:
        script: |
          // get inputs
          const version = "${{ inputs.version }}"
          const prefix = "${{ inputs.prefix }}"
          console.log(version)

          // extract major version number
          const prefixRe = new RegExp(`^${prefix}`)
          const versionNumber = `${version}`.replace(prefixRe, "")
          const major = versionNumber.substring(0, versionNumber.indexOf("."))
          console.log(major)

          // retrieve info about input tag to get sha
          core.info(`Retrieving info for tag ${version}...`)
          const tagParams = {
               owner: context.repo.owner,
               repo: context.repo.repo,
               ref: `tags/${ version }`,
          }
          console.log(tagParams)
          const { data: {object: {sha} } } = await github.rest.git.getRef(tagParams)
          console.log(sha)

          // try to create major version tag
          core.info(`Creating or updating major version ${major}...`)
          let majorTag
          // create major version tag
          const createRefParams = {
            ...context.repo,
            ref: `refs/tags/${prefix}${major}`,
            sha
          }
          console.log("createRefParams", createRefParams)
          majorTag = await github.rest.git.createRef(createRefParams)
          console.log(majorTag)
